revive/app/__init__.py
from flask import Flask

import mysql.connector 


# db = list()
db = mysql.connector.connect( # LLAMAMOS AL FUNCION CONNECT PARA CONECTARNOS
    host ='informatica.iesquevedo.es',
    port = 3333,
    user ='root', #USUARIO QUE USAMOS NOSOTROS
    password ='1asir', #CONTRASEÑA CON LA QUE NOS CONECTAMOS
    database='patri'
) 



def create_app():
    app = Flask(__name__)
    app.debug = True
    

    

    from .routes import routes

    app.register_blueprint(routes.rutas_usuarios)

    return app

revive/app/routes/routes.py
from app import db
from flask import Flask, render_template, request, redirect, url_for, Blueprint

from app.data.infoUsuarios  import Usuario
from app.data.infoProductos import Producto  # PARA PODER ACCEDER A LOS DIRECTORIOS DE UNA MANERA FÁCIL 


rutas_usuarios = Blueprint("routes", __name__)

@rutas_usuarios.route('/')  # ESTO ES LA RUTA PRINCIPAL DE NUESTRA APP SE PONE CON LA BARRA
def home():
    infoUsuarios : Usuario = Usuario(db)
    return render_template('index.html', data=infoUsuarios.dameTodos())  # PARA QUE SALGA NUESTRO INDEX AL INICIO #DATA=INSERTOBJECT ES PARA QUE NOS SALGA EN NUESTRO HTML


@rutas_usuarios.route('/user', methods=['POST'])
def addUser():
    nombre = request.form['nombre'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON EL NOMBRE QUE INDIQUEMOS
    apellido = request.form['apellido'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON EL password QUE INDIQUEMOS
    email = request.form['email'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON EL NOMBRE QUE INDIQUEMOS
    usuario : Usuario = Usuario(db)
    usuario.añadirUsuario(nombre,apellido,email)
    return redirect(url_for('routes.home')) # Y REDIRIGIMOS A HOME DE NUEVO. REDIRECT Y URL_FOR LO TENEMOS QUE IMPORTAR DE FLASK

    
@rutas_usuarios.route('/delete/<string:idusuario>')
def delete(idusuario):
    usuario : Usuario = Usuario(db)
    usuario.borrarUsuario(idusuario)
    return redirect(url_for('routes.home')) # Y REDIRIGIMOS A HOME DE NUEVO. REDIRECT Y URL_FOR LO TENEMOS QUE IMPORTAR DE FLASK


@rutas_usuarios.route('/productos')  # ESTO ES LA RUTA PARA VER LAS NOTAS DE LOS ALUMNOS EN MI APP SE PONE CON LA BARRA
def productos():
    infoProductos : Producto = Producto(db)
    return render_template('producto.html', data=infoProductos.dameProducto())  # PARA QUE SALGA NUESTRO INDEX AL INICIO #DATA=INSERTOBJECT ES PARA QUE NOS SALGA EN NUESTRO HTML


@rutas_usuarios.route('/userProductos', methods=['POST'])
def addProductos():
    idusuario = request.form['idusuario'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON EL CODIGO ALUMNO QUE INDIQUEMOS
    titulo = request.form['titulo'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON LA NOTA QUE INDIQUEMOS
    estado = request.form['estado'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON LA NOTA QUE INDIQUEMOS
    producto : Producto = Producto(db)
    producto.añadeProducto(idusuario,titulo,estado)
    return redirect(url_for('routes.productos')) # Y REDIRIGIMOS A HOME DE NUEVO. REDIRECT Y URL_FOR LO TENEMOS QUE IMPORTAR DE FLASK


@rutas_usuarios.route('/deleteProductos/<string:idusuario>')
def deleteProductos(idusuario):
    producto : Producto = Producto(db)
    producto.borrarProducto(idusuario)
    return redirect(url_for('routes.productos')) # Y REDIRIGIMOS A HOME DE NUEVO. REDIRECT Y URL_FOR LO TENEMOS QUE IMPORTAR DE FLASK

revive/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Revive</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    
    {% endblock %}
    
</head>
<body>
    {% block content %}
    {% endblock %}

</body>
</html>

revive/app/templates/index.html
{% extends "base.html" %}
{% block title %}Informacion Usuario{% endblock %}


{% block content %}
    <h3 class="display-4 text-center mt-5 mb-5 text-success">Nuevo Registro PARA GITHUBACTIONS</h3>
    <div class="container">
      <div class="card shadow"> 

        <form class="row g-3" action="/user" method="POST">

            <!-- Controles: Nombre, email -->
         <div>
         <div class="bg-secondary p-2 text-dark bg-opacity-10" > 
         <div class="lead row mb-3">
          
            <div class="col">
            <label>Nombre</label> 
            <input placeholder="Nombre" class="form-control mb-3" type="text" name="nombre"/>
        
            </div>

            <div class="col">
            <label>Apellido</label> 
            <input placeholder="Apellido" class="form-control mb-3" type="text" name="apellido"/>
            </div>

            <div class="col">
            <label>Email</label>
             <input placeholder="Email" class="form-control mb-3" type="text" name="email"/>
            </div>
              
  
            <div class="col">
            <input type="submit" value="Añadir" class="btn btn-success mb-5 mt-4"/>
            </div>
        </div> 
        </div>
        </div>


        </form>  
    </div>

        <br>
        <h3 class="display-6">Usuarios</h3>

        <div class="row" >
        <table class="table table-group-divider table-striped">      
            
            <thead>
                <tr class="lead table-warning">
                    <th scope="col">ID Usuario</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Email</th>
                    <th scope="col">Eliminar Usuario</th>
                
                </tr>
            </thead>
            <br>
            <br>
            
            <tbody>
                {% for d in data %} <!-- ESTE BUCLE SIRVE PARA ENVIAR LOS DATOS . POR CADA UNO DE LOS ELEMENTOS DE DATA LO VAMOS A IR IMPRIMIENDO DENTRO DE DATA-->
                    <tr class="lead table table-striped">
                        <td>{{d.idusuario}}</td>  <!-- LAS DOBLES LLAVES ES PARA ACCEDER A LOS DATOS. CON EL '.' ACCEDEMOS AL DATO EN CONCRETO -->
                        <td>{{d.nombre}}</td>
                        <td>{{d.apellido}}</td>
                        <td>{{d.email}}</td>
                        <td><a href="{{url_for('routes.delete',idusuario=d.idusuario)}}"  class="btn btn-outline-danger btn-sm">Eliminar</a></td>
                        
                    </tr>
                    {% endfor %}
            </tbody>
        
      </table>
     </div>
     <td><a href="{{url_for('routes.productos')}}" class="lead link-success"><b>Añadir Producto</b></a></td>
     <br>
     <br>
    </div>



{% endblock %}

revive/app/templates/producto.html
{% extends "base.html" %}
{% block title %} Información Producto {% endblock %}


{% block content %}
    
<h2 class="display-4 text-center mt-5 mb-5 text-success">Añadir Producto</h2>

    <div class="container">

        <div class="card shadow"> 

        <form action="/userProductos" method="POST" class="row g-3">

            <!-- Controles: Nombre, email -->
    
        <div>
        <div class="bg-secondary p-2 text-dark bg-opacity-10">

        <div class="lead row mb-3">

            <div class="col">
            <label>ID Usuario</label> 
            <input placeholder="ID Usuario" class="form-control mb-3" type="text" name="idusuario"/>
            </div>
            <div class="col"> 
            <label>Título</label> 
            <input placeholder="Ej: Taburete Infantil" class="form-control mb-3" type="text" name="titulo"/>
            </div> 
            <div class="col">
            <label>Estado</label>
            <input placeholder="Nuevo o Usado / Pequeña descripción"  class="form-control mb-3" type="text" name="estado"/>
            </div>
            <div class="col">
            <input type="submit" value="Añadir Producto" class="btn btn-success mb-5 mt-4"/>
            </div>
        </div>
        </div>
        </div>
        </form>
        </div>

        <br>
        <h3 class="display-6">Productos</h3>

       <div class="row">
        <table class="table table-group-divider table-striped">
            <thead class="lead">
                <tr class="table-warning">
                    <th scope="col">ID Usuario</th>
                    <th scope="col">Título</th>
                    <th scope="col">Estado</th>
                    <th scope="col">Eliminar Producto</th>
                
                </tr>
            </thead>

            <br>
        
            <tbody>
                {% for d in data %} <!-- ESTE BUCLE SIRVE PARA ENVIAR LOS DATOS . POR CADA UNO DE LOS ELEMENTOS DE DATA LO VAMOS A IR IMPRIMIENDO DENTRO DE DATA-->
                    <tr class="lead table table-striped">
                        <td>{{d.idusuario}}</td>  <!-- LAS DOBLES LLAVES ES PARA ACCEDER A LOS DATOS. CON EL '.' ACCEDEMOS AL DATO EN CONCRETO -->
                        <td>{{d.titulo}}</td>
                        <td>{{d.estado}}</td>
                        <td><a href="{{url_for('routes.deleteProductos',idusuario=d.idusuario)}}" class="btn btn-outline-danger btn-sm">Eliminar</a></td>
                        
                    </tr>
                    {% endfor %}
            </tbody>
        </table>
      </div> 
      <td><a href="{{url_for('routes.home')}}" class="lead link-success"><b>Registrar Nuevo Usuario</b></a></td>
      <br>
      <br>
      </div>  
   


{% endblock %}